http:
  routers:
    platform-api:
      rule: >-
        (Host(`building-land.com`) || Host(`www.building-land.com`)) &&
        (PathPrefix(`/api/mobile/v1`) || PathPrefix(`/api/store/legacy/v1/notifications/`) || Path(`/api/v1/environment-analysis`) ||
        PathPrefix(`/api/v1/report-archives`) || PathPrefix(`/api/v1/reports/`) ||
        PathPrefix(`/api/v1/account/`) ||
        (PathPrefix(`/api/report-archive`) && HeaderRegexp(`Authorization`, `(?i)^Bearer[ ]+.+`)))
      service: api
      priority: 200
      entryPoints:
        - web
        - tunnel
    homepage:
      rule: Host(`building-land.com`) || Host(`www.building-land.com`)
      service: homepage
      entryPoints:
        - web
        - tunnel
    api:
      rule: PathPrefix(`/`)
      service: api
      entryPoints:
        - web
        - tunnel
    traefik-dashboard:
      rule: PathPrefix(`/traefik`)
      service: api@internal
      entryPoints:
        - web
        - tunnel

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://api:8000"
    homepage:
      loadBalancer:
        servers:
          - url: "http://web:5180"
